spring.application.name=patient-service

# Uncomment this to use in memory database
#spring.h2.console.enabled=true
#spring.h2.console..path=/h2-console
#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.driver-class-name=org.h2.Driver
#
#spring.datasource.username=admin
#spring.datasource.password=password
#
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#
#spring.jpa.hibernate.ddl-auto=update
#spring.sql.inti.mode=always

server.port=4000
logging.level.root=info

billing.service.address=${BILLING_SERVICE_ADDRESS:billing-service}
billing.service.grpc.port=${BILLING_SERVICE_GRPC_PORT:9001}
